package commands

type cmdInfo struct {
	Cmd    string
	Desc   string
	Syntax string
}

type CmdsInfo struct {
	Cat  string
	Cmds []cmdInfo
}

var Commands = []CmdsInfo{
	{
		Cat: "STRING",
		Cmds: []cmdInfo{
			{"SET", "SAVE STRING VALUE BY KEY", "SET [K] V"},
			{"MSET", "SAVE MULTIPLE STRING VALUES BY KEYS", "MSET [K V]..."},
			{"GET", "GET SINGLE VALUE BY KEY", "GET [K]"},
			{"MGET", "GET MULTIPLE VALUES BY KEYS", "MGET [K]..."},
		},
	},
	{
		Cat: "GENERAL",
		Cmds: []cmdInfo{
			{"DEL", "DELETE KEYS FROM CACHE", "DEL [K]..."},
			{"COPY", "COPY VALUE FROM ONE KEY TO ANOTHER", "COPY [S_K] [T_K]"},
			{"RENAME", "RENAME A KEY IN THE CACHE", "RENAME [OLD_KEY] [NEW_KEY]"},
			{"TYPE", "SHOW THE DATA TYPE OF A KEY", "TYPE [K]"},

			{"KEYS", "GET KEYS BY PATTERN", "KEYS [PATTERN] (COUNT [N])"},

			{"LIST", "GET ALL KEY NAMES", "LIST"},
			{"LISTLEN", "GET THE NUMBER OF ELEMENTS", "LISTLEN"},

			{"EXISTS", "CHECK IF THE KEYS EXIST AND RETURN COUNT", "EXISTS [K]..."},
			{"LEXISTS", "CHECK IF THE KEYS EXIST AND RETURN LIST", "LEXISTS [K]..."},
		},
	},
	{
		Cat: "NUMERIC",
		Cmds: []cmdInfo{
			{"INCR", "INCREASE THE NUMBER BY 1", "INCR [K]"},
			{"INCRBY", "INCREASE THE NUMBER BY N", "INCRBY [K] N"},
			{"DECR", "DECREASE THE NUMBER BY 1", "DECR [K]"},
			{"DECRBY", "DECREASE THE NUMBER BY N", "DECRBY [K] N"},
			{"MUL", "MULTIPLY THE NUMBER BY N", "MUL [K] N"},
			{"DIV", "DIVIDE THE NUMBER BY N", "DIV [K] N"},
		},
	},
	{
		Cat: "LIST",
		Cmds: []cmdInfo{
			{"ESET", "CREATE EMPTY LIST", "ESET L_NAME"},
			{"LSET", "SET VALUES BY INDEX IN LIST", "LSET L_NAME [I V]..."},
			{"LGET", "GET VALUES BY INDEX IN LIST", "LGET L_NAME [I]..."},
			{"LCLEAR", "CLEAR LIST", "LCLEAR L_NAME"},
			{"LLEN", "GET LIST LENGTH", "LLEN L_NAME"},
			{"SPUSH", "PUSH VALUES TO START OF LIST", "SPUSH L_NAME [V]..."},
			{"EPUSH", "PUSH VALUES TO END OF LIST", "EPUSH L_NAME [V]..."},
			{"SPOP", "REMOVE ELEMENTS FROM THE START OF THE LIST", "SPOP L_NAME [COUNT]"},
			{"EPOP", "REMOVE ELEMENTS FROM THE END OF THE LIST", "EPOP L_NAME [COUNT]"},
			{"SRANGE", "GET LIST VALUES IN RANGE", "SRANGE L_NAME [F_I] [T_I]"},
			{"CONTAINS", "CHECK IF THE VALUES EXIST AND RETURN COUNT", "CONTAINS L_NAME [V]..."},
			{"LCONTAINS", "CHECK IF THE VALUES EXISTS AND RETURN LIST", "LCONTAINS L_NAME [V]..."},
			{"INDEXOF", "RETURN INDEX OF TARGET VALUE IN LIST", "INDEXOF L_NAME [V]"},
		},
	},
	{
		Cat: "HASH",
		Cmds: []cmdInfo{
			{"HSET", "SET HASH FIELDS", "HSET H_NAME [K V]..."},
			{"HGET", "GET HASH FIELDS VALUES", "HGET H_NAME [K]..."},
			{"HDEL", "DELETE HASH FIELDS", "HDEL H_NAME [K]..."},
			{"HLEN", "GET NUMBER OF FIELDS IN HASH", "HLEN H_NAME"},
			{"HKEYS", "GET ALL HASH FIELD NAMES", "HKEYS H_NAME"},
			{"HVALUES", "GET ALL HASH FIELD VALUES", "HVALUES H_NAME"},
			{"HCONTAINS", "CHECK IF THE KEYS EXIST AND RETURN COUNT", "HCONTAINS H_NAME [K]..."},
			{"LHCONTAINS", "CHECK IF THE KEYS EXIST AND RETURNS LIST", "LHCONTAINS H_NAME [K]..."},
		},
	},
	{
		Cat: "SET",
		Cmds: []cmdInfo{
			{"SADD", "ADD ELEMENTS TO THE SET", "SADD S_NAME [V]..."},
			{"SREM", "REMOVE ELEMENTS FROM THE SET", "SREM S_NAME [V]..."},
			{"SLEN", "GET THE NUMBER OF ELEMENTS IN THE SET", "SLEN S_NAME"},
			{"SMEMBERS", "GET ALL ELEMENTS IN THE SET", "SMEMBERS S_NAME"},
			{"SCONTAINS", "CHECK IF THE ELEMENTS EXIST AND RETURN COUNT", "SCONTAINS S_NAME [V]..."},
			{"LSCONTAINS", "CHECK IF THE ELEMENTS EXIST AND RETURN LIST", "LSCONTAINS S_NAME [V]..."},
		},
	},
	{
		Cat: "ZSET",
		Cmds: []cmdInfo{
			{"ZADD", "ADD ELEMENT WITH SCORE TO SORTED SET", "ZADD Z_NAME [V] [SCORE]"},
			{"ZREM", "REMOVE ELEMENT FROM SORTED SET", "ZREM Z_NAME [V]"},
			{"ZRANGE", "GET ELEMENTS FROM SORTED SET BY SCORE RANGE", "ZRANGE Z_NAME MIN MAX"},
			{"SCORE", "GET SCORE OF ELEMENT IN SORTED SET", "SCORE Z_NAME [V]"},
			{"LSCORE", "GET SCORES OF MULTIPLE ELEMENTS IN SORTED SET", "LSCORE Z_NAME [V]..."},
			{"SLEN", "GET THE NUMBER OF ELEMENTS IN THE ZSET", "SLEN Z_NAME"},
			{"SMEMBERS", "GET ALL ELEMENTS IN THE SET", "SMEMBERS Z_NAME"},
			{"SCONTAINS", "CHECK IF THE ELEMENTS EXIST AND RETURN COUNT", "SCONTAINS Z_NAME [V]..."},
			{"LSCONTAINS", "CHECK IF THE ELEMENTS EXIST AND RETURN LIST", "LSCONTAINS Z_NAME [V]..."},
		},
	},
	{
		Cat: "EXPIRATION",
		Cmds: []cmdInfo{
			{"TTK", "SET DATA LIFESPAN BEFORE DELETING", "TTK [K] TIME"},
			{"TTL", "TIME LEFT BEFORE DATA IS DELETED", "TTL [K] TIME"},
		},
	},
	{
		Cat: "SERVER",
		Cmds: []cmdInfo{
			{"MODE", "CHANGE THE MODE OF THE CACHE", "MODE [READONLY/READWRITE]"},
			{"PING", "CHECK IF THE CACHE SERVER IS ALIVE", "PING"},
		},
	},
	{
		Cat: "CONSOLE",
		Cmds: []cmdInfo{
			{"CLS", "CLEARE ALL OUTPUT", "CLS"},
		},
	},
}
